### PR TITLE
Adding support for nodejs 7.3.x

### PR DESCRIPTION
**Pull request by ascii27**
This update adds support for the node module version 51 (nodejs 7.3)

### CODE REVIEW

**Comment by rla** [comment]
I have taken a fork by @Sleepyowl that added NAN to make it buildable for other Node.js versions and published the new codebase as the `swipl` package. I also tried to fix and document as many issues as I found. I also took and added ideas from various other forks of this codebase. The original authors seem to have disappeared. https://github.com/rla/node-swipl

**Comment by sebgod** [comment]
@rla , I think it would be better if there was a node-swipl2 repository where every addition that people made and are not in the abandoned repository.

**Comment by rla** [comment]
Seems like mine is still the latest and I have time to maintain it. I hope that potential contributors find it from these comments.

**Comment by sebgod** [comment]
@rla, Keep up the good work :)

**Comment by kloni** [comment]
Hi guys,
sorry for my absence. Great to see this little project still alive. Thank you all.
If you'd like to adopt this repo, how about transferring it?

**Comment by rla** [comment]
@sebgod, @kloni, maybe add a link+text to README to direct the user to live fork(s). Searching for "swipl "or "prolog" on NPM turns up my fork anyway, so it might not be that important. This repo also has 3 open PRs where authors might have got no feedback at all.

**Comment by ascii27** [comment]
Given that @rla is planning to keep this work alive elsewhere, I'll close my PR.

**Pull request closed without merging**
